name: Deploy website on push

on: 
  push:
    branches:
      - main
      
jobs:
  web-deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    
    steps: 
    - name: Get latest code
      uses: actions/checkout@v2
      
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with: 
        server: api.hmifamikom.org
        host: api.hmifamikom.org
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: /public_html/api.hmifamikom.org/
        exclude: |
          .env
          public/files/**
